openapi: 3.0.0
info:
  title: Timebank
  description: Timebank API documentation
  version: '1.0'

security:
  - bearerAuth: []
  
paths:
  /v1/system/ping:
    get:
      operationId: ping
      summary: Replies with pong
      description: Replies ping with pong
      tags: 
        - System
      responses:
        "200":
          description: Pong
          content:
            text/plain:
              schema:
                type: string
                
  /v1/persons:
    get:
      operationId: listPersons
      summary: Get list of Timebank persons.
      description: Get list of Timebank persons.
      tags: 
        - Persons
      parameters:
        - name: active
          in: query
          description: Filter by persons active state
          schema:
            type: boolean
      responses:
        "200":
          description: Get list of Timebank persons.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Person"
        "default":
          description: Invalid request was sent to the server.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/dailyEntries:
    get:
      operationId: listDailyEntries
      summary: Lists daily time entries.
      description: Lists daily time entries.
      tags:
        - DailyEntries
      parameters:
        - name: personId
          in: query
          description: Filter by persons unique ID
          schema:
            type: integer
            format: int32
        - name: before
          required: false
          in: query
          description: Retrieve time entries before given date.
          schema:
            type: string
            format: date
        - name: after
          required: false
          in: query
          description: Retrieve time entries after given date.
          schema:
            type: string
            format: date
      responses:
        "200":
          description: List of time entries.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DailyEntry'
        "default":
          description: Invalid request was sent to the server.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/synchronize:
    post:
      operationId: synchronizeTimeEntries
      summary: Synchronizes time entries from Forecast API.
      description: Retrieves and synchronizes time entries from Forecast API.
      tags:
        - Synchronize
      parameters:
        - name: before
          required: false
          in: query
          description: Synchronizes before given date.
          schema:
            type: string
            format: date
        - name: after
          required: false
          in: query
          description: Synchronizes after given date.
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Synchronized time entries from Forecast API.
          content:
            text/plain:
              schema:
                type: string
        "default":
          description: Invalid request was sent to the server.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        
  /v1/persons/{personId}/total:
    get:
      operationId: listPersonTotalTime
      summary: Lists persons total time entries.
      description: Lists persons total time entries.
      tags:
        - Persons
      parameters:
        - name: personId
          required: true
          in: path
          schema:
            type: integer
            format: int32
        - name: timespan
          required: false
          in: query
          description: Default value is ALL_TIME.
          schema:
            $ref: "#/components/schemas/Timespan"
      responses:
        "200":
          description: |-
            When getting total from all the time,
                              _id field will be null, otherwise it will be
                              combination of year and month or year and week
                              depending on timespan parameter
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PersonTotalTime"
        "default":
          description: Invalid request was sent to the server.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  schemas:
    Error:
      type: object
      description: Error object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
          
    Timespan:
      type: string
      description: Enum for timespan
      enum: 
        - ALL TIME
        - YEAR
        - MONTH
        - WEEK
          
    Person:
      type: object
      description: Person Data from Forecast API
      required:
        - id
        - firstName
        - lastName
        - monday
        - tuesday
        - wednesday
        - thursday
        - friday
        - saturday
        - sunday
        - active
        - startDate
      properties:
        id:
          type: integer
          format: int32
          description: Person ID in Forecast.
        firstName:
          type: string
          description: Person first name.
        lastName:
          type: string
          description: Person last name.
        monday:
          type: integer
          format: int32
          description: Persons expected working hours in minutes.
        tuesday:
          type: integer
          format: int32
          description: Persons expected working hours in minutes.
        wednesday:
          type: integer
          format: int32
          description: Persons expected working hours in minutes.
        thursday:
          type: integer
          format: int32
          description: Persons expected working hours in minutes.
        friday:
          type: integer
          format: int32
          description: Persons expected working hours in minutes.
        saturday:
          type: integer
          format: int32
          description: Persons expected working hours in minutes.
        sunday:
          type: integer
          format: int32
          description: Persons expected working hours in minutes.
        active:
          type: boolean
          description: Defining is person active e.g. is employeed.
        defaultRole:
          type: integer
          format: int32
          description: ID of default role.
        startDate:
          type: string
          description: Start date of employment, String.

    DailyEntry:
      type: object
      description: Person's daily entry
      required:
        - person
        - internalTime
        - projectTime
        - logged
        - expected
        - balance
        - date
      properties:
        person:
          type: integer
          format: int32
          description: Person ID in Forecast
        internalTime:
          type: integer
          format: int32
          description: Amount of internal time per time entry
        projectTime:
          type: integer
          format: int32
          description: Amount of project time per time entry
        logged:
          type: integer
          format: int32
          description: Amount of time logged per time entry
        expected:
          type: integer
          format: int32
          description: Amount of time expected per time entry
        balance:
          type: integer
          format: int32
          description: Total amount of worktime per time entry
        date:
          type: string
          format: date
          description: Date of time entry

    PersonTotalTime:
      type: object
      description: Person's total time
      required:
        - balance
        - logged
        - expected
        - internalTime
        - projectTime
      properties:
        personId:
          type: integer
          format: int32
        balance:
          type: integer
          format: int32
          description: Difference between expected and logged time.
        logged:
          type: integer
          format: int32
          description: Total amount logged time of person.
        expected:
          type: integer
          format: int32
          description: Total amount expected time of person.
        internalTime:
          type: integer
          format: int32
          description: Total amount of internal time of person.
        projectTime:
          type: integer
          format: int32
          description: Total amount of project time of person.
        year:
          type: integer
          format: int32
        monthNumber:
          type: integer
          format: int32
        weekNumber:
          type: integer
          format: int32

    TimeEntry:
      type: object
      description: Person's single time entry
      required:
        - entryId
        - forecastId
        - person
        - internalTime
        - projectTime
        - date
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
          description: ID of DailyEntry in UUID
        forecastId:
          type: integer
          format: int32
          description: TimeEntry ID in Forecast
        person:
          type: integer
          format: int32
          description: Person ID in Forecast
        internalTime:
          type: integer
          format: int32
          description: Amount of internal time per time entry
        projectTime:
          type: integer
          format: int32
          description: Amount of project time per time entry
        date:
          type: string
          format: date
          description: Date of time entry
        createdAt:
          type: string
          format: date-time
          description: Date time of time entry registration
        updatedAt:
          type: string
          format: date-time
          description: Date time of time entry update
